### ISSUE TITLE
Coin Swapped

### ISSUE THREAD

**Issue by TRBO-Coin** [TurboStake/TurboStake#1]
New Team of 2018 Swapped TurboStake coin to TRBO in July 2019 - This coin is no longer listed on any exchanges and no further development will take place.

**80% of this coin supply was burned and balances swapped.**

###  Swap has finished and there is no development on this coin, New TRBO Info https://trbo.cc

**Comment by 5mil** [comment]
> New Team of 2018 Swapped TurboStake coin to TRBO in July 2019 - This coin is no longer listed on any exchanges and no further development will take place.
> 
> **80% of this coin supply was burned and balances swapped.**
> 
> ###  Swap has finished and there is no development on this coin, New TRBO Info https://trbo.cc

That's cute. You never burned my coins so I guess I can continue the actual coin on beyond your "swap scheme". (You probably "burned" it to a wallet that you have control of). Also, it's not possible that you collected 80% of the coin supply. Anyways, we may attempt at redeveloping this and Sprouts after both suffered a fake "swap" takeover. Honestly after that scammy stuff I'm not opposed to completely reworking the coin in the ways we want, upgrading, and rebooting the chain. The old ledger is compromised by those scammers who ran as soon as they dumped the coin on an exchange. As far as I'm concerned we still hold the rights to develop both Sprouts and turbostake.

**Comment by TRBO-Coin** [comment]
That is funny nearly 5 years on and you say it was a fake swap, all coins that were sent at the time where swapped and burned. Things have moved on since 5 years ago, the coin is now a token so there was no FAKE swap you need to ensure you get your facts right before you accuse of things being fake.

You can do what you like with the coin but accusations like this are not okay, there was plenty of information regarding the swap of Turbostake to TRBO and to the current token so please do your research.

**Comment by 5mil** [comment]
> That is funny nearly 5 years on and you say it was a fake swap, all coins that were sent at the time where swapped and burned. Things have moved on since 5 years ago, the coin is now a token so there was no FAKE swap you need to ensure you get your facts right before you accuse of things being fake.
> 
> You can do what you like with the coin but accusations like this are not okay, there was plenty of information regarding the swap of Turbostake to TRBO and to the current token so please do your research.

Cool story bro. You mean you moved on to a new scam? Where's the coin? Website? Verifiable burn records?

**Comment by TRBO-Coin** [comment]
I am not going to argue over what is fact or not, but there is a lot of information regarding the initial swap from Turbostake > TRBO and TRBO to MMT which is the currency now. https://moments.market is the website for the token it is today which is going through development direction change and we have never sold any currency on exchanges so please provide proof of your claims, calling us a scam is slander so please get your proof ready.

We have as the team that took over Turbostake 5 years ago have continued the development even though it has gone through swaps. I don't have swap proof as there is no explorer for the coin or coins. It has never been a scam in the 5 years our team has been on this currency or current currency.

Obviously you have not done any searches or research on the currency and see then numerous posts on numerous sites regarding the Swaps so i am not going to explain myself to you, call it what you will but the community who has actually been part of it for the 5 years know better and still active. Restart the chain whatever you want and you can see for yourself the proof that we burned 80% of which was submitted to us 5 years ago.

**Comment by 5mil** [comment]
What would give any of you the idea that what you did "turning a coin into a token" is an actual swap? The owners of the codebase and those that released the code are the ones which have the actual right to do that type of thing.. which isn't you. So whatever you guys think you did is cute but trbo is coming back
 Thx

**Comment by TRBO-Coin** [comment]
When we took over the development of this coin it was abandoned so i don't really care what you think, but you do need to do your research as you know absolutely nothing about any of the swaps as we did not swap straight to a token so again you know nothing about what happened, but i don't care what you do, you are free to do as you wish with this coin.

**Comment by 5mil** [comment]
> When we took over the development of this coin it was abandoned so i don't really care what you think, but you do need to do your research as you know absolutely nothing about any of the swaps as we did not swap straight to a token so again you know nothing about what happened, but i don't care what you do, you are free to do as you wish with this coin. 

Still not your call and you "swapped" it so you admittedly abandoned the project. So I'm not sure why you replied at all
